######################## default configuration ####################
baseURL = "https://zectedu.netlify.app/"
title = "ZectEdu : Leading Education Website"
theme = "zect-edu"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
metaDataFormat = "yaml"



############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "course"
URL = "course"
weight = 2

[[menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[menu.main]]
  parent = "Pages"
  name = "teacher"
  URL = "teacher"

  [[menu.main]]
  parent = "Pages"
  name = "notice"
  URL = "notice"

  [[menu.main]]
  parent = "Pages"
  name = "event"
  URL = "event"

  [[menu.main]]
  parent = "Pages"
  name = "scholarship"
  URL = "scholarship"

  [[menu.main]]
  parent = "Pages"
  name = "research"
  URL = "research"
  
[[menu.main]]
name = "blog"
URL = "blog"
weight = 4
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5


# footer menu

[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"


#################### default parameters ################################
[params]
    #logo-default
    logo = "images/logo.png"
    #logo-white
    #logo = "images/logoWhite.png"
    logoWhite = "images/logoWhite.png"
    # Meta data
    description = "Tema Pendidikan ZectStudio"
    author = "ZectStudio"
    dateFormat = " 02 January 2006"
    # contact info
    address = "Yogyakarta"
    mobile = "+6285156652396"
    email = "wearezecter@gmail.com"
    # contact form action
    contact_form_action = "#" # contact form works with https://formspree.io
    # Google Analitycs
    google_analitycs_id = "" # your id
    # top header
    top_header = true
    
    #standard-theme :
    style = "scss/style.scss"
    
    #dark-theme :
    #style = "scss-dark/style.scss"
    
    #shinninghopper-theme :
    #style = "scss-shinninghopper/style.scss"


    #hero.html
    [params.hero]
        enable = true
        [[params.slider_item]]
            title = "ZectEdu"
            content = "Sebuah usaha kami membantu memajukan dunia pendidikan Indonesia. Setiap warga negara berhak atas pendidikan yang layak dan setiap sekolah pantas untuk dapat memiliki media untuk menyebarluaskan ilmunya kepada semua elemen masyarakat. Kami di sini untuk membantu pendidikan"
            button = true
            
        [[params.slider_item]]
            title = "ZectEdu"
            content = "Sebuah dukungan kami terhadap kemajuan pendidikan Indonesia. Setiap anak bangsa berhak atas kemerdekaan atas mempelajari sesuai dengan minat dan bakat mereka. Kami di sini untuk membantu mereka"
            button = true
            
        [[button]]
            enable = true
            
    #hero-slider.html
    [params.heroslider]
        enable = true
        image = "images/banner/banner-feature.png"
        
        [[params.feature_item]]
            icon = "ti-book"
            name = "Tekun"
            content = "Setiap anak didik diharapkan memiliki sikap tekun agar mampu meraih ilmu sebanyak-banyaknya"
        
        [[params.feature_item]]
            icon = "ti-blackboard"
            name = "Berbagi Ilmu"
            content = "Ilmu yang telah didapat diharapkan dapat memberi terang bagi masyarakat sekitar."
        
        [[params.feature_item]]
            icon = "ti-agenda"
            name = "Berprestasi"
            content = "Setiap anak didik dapat memiliki keunggulan dan siap untuk bersaing dengan peserta didik lain"
        
        [[params.feature_item]]
            icon = "ti-write"
            name = "Berakhlak"
            content = "Wawasan budi pekerti juga diberikan agar anak didik menjadi manusia yang memiliki nilai kemanusiaan yang tinggi."
            
    #about-sm.html
    [params.aboutsm]
        enable = true
        title = "Tentang ZectEdu"
        content = "Sebuah layanan yang dikembangkan oleh ZectStudio.id untuk memberikan kemudahan akses penyebaran info edukatif bagi sekolah-sekolah di seluruh Indonesia"
        
    #course.html
    [params.course]
        enable = true
        title = "Kurikulum"
        
    #cta.html
    [params.cta]
        enable = true
        subtitle = "Berminat?"
        title = "Hubungi Kami"
    
    #success-story.html
    [params.story]
        enable = true
        title = "Cerita Sukses"
        content = "Kisah alumni kami yang sukses menekuni bisnis pengembangan AI"
        
    #event.html
    [params.event]
        enable = true
        title = "Acara Sekolah"
        
    #blog.html
    [params.blog]
        enable = true
        title = "Blog Sekolah"
        
# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.


# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[taxonomies]
  category = "Kategori"
  tag = "tags"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [ZectStudio](https://zectstudio.id)"

